### ISSUE TITLE
Is build.fox a python file?

### ISSUE THREAD

**Issue by xpac27** [beardsvibe/buildfox#123]
If not then forget about this :)

But if so, why not having a `.py` extension? (something like `buildfox.py` or even `.buildfox.py` a bit like [they](http://valloric.github.io/YouCompleteMe/#c-family-semantic-completion-engine-usage) do). It would be a good indication regarding how to format the file and it would allow syntax colouring (which would make [this](https://github.com/xpac27/TinyWorld/blob/master/build.fox) look nicer) and syntax checking in IDEs.

**Comment by den-mentiei** [comment]
It's not :)
But we should create some syntax files for popular editors, for sure!

**Comment by den-mentiei** [comment]
#124

**Comment by xpac27** [comment]
Alright ;)

## 

Vincent Cogne
