### ISSUE TITLE
Cross platform file extensions

### ISSUE THREAD

**Issue by jimon** [beardsvibe/buildfox#18]
Currently we don't control extensions at all, so we just write :

```
build *.obj: auto *.cpp
build app.exe: auto *.obj
```

But how it will look like for other platforms ? Would be nice to avoid redundancy.

**Comment by den-mentiei** [comment]
Good point.

Can we just have obj_ext variable in core for each toolchain?
We just need to make it look good in rule definitions.

**Comment by jimon** [comment]
We will, but this is not enough.
This one just looks ugly :

```
build *${obj}: auto *.cpp
build app${exe}: auto *${obj}
```

Maybe we need some better way of defining this. Like auto extension replace or something ?
.exe and .obj are self explanatory more or less, we can rename them to other extensions on other targets.

**Comment by den-mentiei** [comment]
Myabe we can have some kind of template rule to call (per each toolchain):

```
# in core
builder cpp *.obj: auto *.cpp

# in user fox file
build cpp src/**/*
build cpp tests/*
```

**Comment by jimon** [comment]
More ideas :

1) Use transformers as expansion macroses

```
transformer obj: ${param}.obj
transformer exe: ${param}.exe

build obj(*): auto *.cpp
build exe(app): auto obj(*)
```

2) Add macro definition to build operation

```
# you specify
# target_explicit | target_implicit : inputs_explicit | inputs_implicit | inputs_order
# and all transformations will be applied
extension build_obj: *.obj 
extension build_exe: *.exe : *.obj
extension build_dll: *.dll | *.lib

build_obj *: auto *.cpp
build_exe app: auto *
```

PS. I still not happy with any of them

**Comment by den-mentiei** [comment]
2) seems like my first idea and I'm totally unhappy with it.

1) looks much better and we can give it a try.

Sent from my iPhone
