### ISSUE TITLE
BuildFox general tests

### ISSUE THREAD

**Issue by jimon** [beardsvibe/buildfox#25]
Check if example programs are buildable with BuildFox.

**Comment by jimon** [comment]
Most stuff is tested in #37, but we are not really building anything there yet because gcc core is not available at a moment ...

**Comment by jimon** [comment]
After #10 and #48 we can check all compiler variations in tests.py, so just add all of them.
Plus we should be able to actually build with gcc on travis.

**Comment by den-mentiei** [comment]
That's done for now.

So, we just need to build with gcc/clang on Travis!
