### ISSUE TITLE
Proper escaping of ( and )

### ISSUE THREAD

**Issue by jimon** [beardsvibe/buildfox#36]
We added `name(value)` transformers in paths recently, but they don't support proper escaping of brackets. So it's impossible to use `name$(value$)` now.

**Comment by den-mentiei** [comment]
Maybe we should implement raw string notation and stop bothering with escaping.
Escape sequences have cons such as: it's hard to write and read + we need to implement it here and there.

**Comment by jimon** [comment]
Maybe, and then raw string could be recommended way, currently `r" whatever "` is treated as regex and not as raw string. Though we still need ability to escape that stuff.

**Comment by den-mentiei** [comment]
What stuff?

Can we just ditch escape sequences all along?

**Comment by jimon** [comment]
I mean there should be ability to escape ( and ) just in case if you need to. Changing whole string from normal to raw string just because you need to escape one character is not a good solution.
