### ISSUE TITLE
Deploy

### ISSUE THREAD

**Issue by jimon** [beardsvibe/buildfox#39]
Figure out how we want to deploy, and setup infrastructure for it.

**Comment by jimon** [comment]
How about [PyPI](https://pypi.python.org/pypi) ? This will enable fast installations and easy update.

**Comment by den-mentiei** [comment]
Looks good.

**Comment by jimon** [comment]
Still not sure, would be nice to provide one python file bundled with ninja somehow ...

**Comment by den-mentiei** [comment]
We can bundle packages for multiple platforms. And this should be useful for people, as e.g. ubuntu lacks latest ninja.

**Comment by den-mentiei** [comment]
Also, we need a script to bundle all the BuildFox (and it's tests, maybe) to one file.

**Comment by jimon** [comment]
I don't think whole test suite is needed, but #43 is for sure should be bundled.

**Comment by jimon** [comment]
Ok, so #59 enables us to have single script. Now we need to use something like http://docs.travis-ci.com/user/deployment/releases/ to create releases here.

**Comment by jimon** [comment]
Lol I can't install `gem install travis` it fails to download pry package :/

**Comment by jimon** [comment]
Ok, so it's easier just to upload compiled script by hand.
