### ISSUE TITLE
Auto rule behavior

### ISSUE THREAD

**Issue by den-mentiei** [beardsvibe/buildfox#44]
Currently, `auto` rool won't resolve into multiple rules.
E.g.: If you have different `auto` rules for `*.c` and `*.cpp` you need to write:

```
build obj(*): auto *.c
build obj(*): auto *.cpp
```

instead of 

```
build obj(*): auto *.c *.cpp
```

**Comment by jimon** [comment]
I guess it's impossible to implement if rules dont have `expand = true`, otherwise it should be ok :)

**Comment by jimon** [comment]
I investigated this a bit, and now I don't think we need this, mixed source codebases are not that popular (the only case that I know is when your main project in cpp and some 3rd party libs are in c).

**Comment by jimon** [comment]
A problem with greedy auto is that it's possible to write something like `build *.exe *.obj: auto *.cpp *.obj` and then this will expand into proper set of build commands. This could be ok, but I think it's too easy to abuse, so let's not do it.

I'll fix msvc core so we will require c sources to be compiled separately as well.
