### ISSUE TITLE
Platforms variations

### ISSUE THREAD

**Issue by den-mentiei** [beardsvibe/buildfox#46]
We should have a platform defines: gcc on linux vs mingw on win (system libs, paths, etc.), clang on linux vs osx (.so vs .dylib, etc.).

**Comment by jimon** [comment]
I guess we can just pass OS name/version through environment discovery, will this be enough ?

**Comment by den-mentiei** [comment]
Should be enough.

**Comment by jimon** [comment]
I guess #62 fixes this for now.
