### ISSUE TITLE
Libs variable

### ISSUE THREAD

**Issue by jimon** [beardsvibe/buildfox#57]
I don't really like libs variable because we missed one part - you need to set implicit dependencies anyway, otherwise ninja can start building executable before libraries. So static_lib\with_app example looks ugly now :

```
build $out/obj(*): auto *.cpp
build $out/app(app): auto $out/obj(*) | $out/lib(*)
    libdirs = $out
    libs = test1 test2
```

**Comment by den-mentiei** [comment]
You will need it anyway - to specify 3rd party and system libs.

But it looks really ugly - when it is specified two times.

**Comment by jimon** [comment]
I doubt that we really need libs except for system libs, just check [gcc docs](https://gcc.gnu.org/onlinedocs/gcc/Link-Options.html) : `The only difference between using an -l option and specifying a file name is that -l surrounds library with ‘lib’ and ‘.a’ and searches several directories.`

**Comment by jimon** [comment]
It's not needed, [it builds](https://travis-ci.org/beardsvibe/buildfox/builds/84776717) just fine.
