### ISSUE TITLE
MSVS vs MSVC vs MSC

### ISSUE THREAD

**Issue by jimon** [beardsvibe/buildfox#72]
#71 introduces MSVS keyword for ide, MSVC is used internally to mark Microsoft C/C++ compiler. So what keywords should we use ?

**Comment by den-mentiei** [comment]
MSC is used by the compiler itself - e.g. MSC_VER, etc. We can nust stick to it.

**Comment by den-mentiei** [comment]
Also, MSVS is not common at all, maybe we should change it, too.

**Comment by jimon** [comment]
How do you name the argument then to generate ide project ? `--msc` ?

**Comment by den-mentiei** [comment]
Can we go with -ide=vs2013 ?

**Comment by jimon** [comment]
Yep, this can work, though it's a bit long. Maybe we also should add some aliases like `bf vs2013` and\or `bf vs`.

**Comment by den-mentiei** [comment]
Indeed, I'll work on it in a branch and merge it afterwards.
