### ISSUE TITLE
Do release through pip

### ISSUE THREAD

**Issue by jimon** [beardsvibe/buildfox#75]
Just to simplify deploy & update.

**Comment by jimon** [comment]
We need something similar to https://github.com/codecov/codecov-python/blob/master/setup.py because you can run this package just as "codecov" from command line, without mentioning python or anything.

**Comment by den-mentiei** [comment]
Are you talking about shebang or what? :)

**Comment by jimon** [comment]
It's actually compiles codecov.exe on win and puts in a PATH so you can just run "codecov" from cmd
