### ISSUE TITLE
Transformer syntax may be confusing to new users

### ISSUE THREAD

**Issue by jimon** [beardsvibe/buildfox#76]
If we write something like `build lib/lib(test): auto lib/obj(*)` then it may be confusing. I hope to find another way so it's become more transparent and obvious.

One way to solve is to put whole path in transformer : `build lib(lib/test): auto obj(lib/*)`.

**Comment by den-mentiei** [comment]
:+1: for the whole path as an argument.
But we should think more.

**Comment by jimon** [comment]
So I guess the only part left is just change all examples/docs to use whole path as an argument :+1:
