### ISSUE TITLE
Suggestion: recursive file lookup

### ISSUE THREAD

**Issue by xpac27** [beardsvibe/buildfox#78]
When adding my .cpp files to the obj list I'm doing the following:

```
build out/obj/obj(*): auto lib/src/ecs/*.cpp lib/src/graphic/*.cpp lib/src/utils/*.cpp lib/src/systems/*.cpp
```

It would be nice to have something like that instead:

```
 build out/obj/obj(*): auto lib/src/**/*.cpp
```

Or like that:

```
 build out/obj/obj(*): auto lib/src/**.cpp
```

Or something else :smiley:

**Comment by den-mentiei** [comment]
Wow, Iv'e totally missed to test it out. I want globs to work this way, as well!

**Comment by jimon** [comment]
I like this feature, though I'm afraid that it's not that obvious to implement. The problem is when you run recursive glob into folder that contains folders like .hg/.git/etc, then you want to skip this folders in your glob but glob syntax doesn't support ignore/skip part. So you need to introduce ignore variable, which sucks.

**Comment by jimon** [comment]
So if anyone have good idea about ignoring folders, then I can do it :+1:

**Comment by den-mentiei** [comment]
We don't care about any ignores - user can put his sources in a sub-folder of the repo, so no .hg/.git/.svn will be globbed.

**Comment by jimon** [comment]
Well remember that older .svn put ".svn" subfolder in all subfolders of a project (not only root). So I assume there will be other situations like this that we cannot foresee now.

**Comment by den-mentiei** [comment]
We can think about something as `filter = .git` as a variable scoped for some specific rule with a glob.

**Comment by jimon** [comment]
Yeah this is what I thought, but it's one more control variable, not sure if it's good or bad :(

**Comment by den-mentiei** [comment]
Or we can introduce another transformer or argument(?) to filter the stuff out.

Sent from my iPhone

**Comment by jimon** [comment]
I wish to have it as part of glob wildcard itself, like `dir/**!.svn|.git/*.cpp`, though this looks like perl :D

**Comment by den-mentiei** [comment]
Looks unreadable ;(

**Comment by jimon** [comment]
So here how we can do it :

1) Recursive glob + put all obj files next to .cpp files : `build **/*.obj: auto **/*.cpp`
2) Recursive glob + put all obj files into separate folder : `build folder/*.obj: auto **/*.cpp`, though I need to think how to implement this properly in current case. Please notice that in this example all .obj files will be put into "folder" as just files (not inside subfolders in "folder")
3) If you need to ignore some folders in your recursive glob we need to add syntax like this : https://github.com/isaacs/node-glob

**Comment by den-mentiei** [comment]
(we've discussed this in Slack internally, so I'm :+1:, as a first iteration, at least)
