### ISSUE TITLE
Suggestion: target specific includedirs

### ISSUE THREAD

**Issue by xpac27** [beardsvibe/buildfox#79]
I have 3 targets (my lib, my tests' executable and my application's executable) therefore my includedirs setup looks like that:

```
includedirs = lib/inc lib/src lib/tests/src app/inc
```

It would probably be more clear if I would be able write:

```
includedirs(mylib) = lib/inc lib/src
includedirs(mytests) = lib/tests/src
includedirs(myapp) = app/inc
```

This way it would avoid potential conflicts (like if both app and lib have classes with the same name for example).

**Comment by den-mentiei** [comment]
But you can setup different `includedirs` per each target?

**Comment by xpac27** [comment]
Ho ok. I didn't get how to do it from the manual. Do I have to use rules?

**Comment by den-mentiei** [comment]
You can do something like:

```
build $out/app/obj(*): auto app/*.cpp
    includedirs = lib/inc
```

**Comment by jimon** [comment]
Feature is there, we just need to document it more.

**Comment by xpac27** [comment]
Haaaa ok :) I get it now. Awesome. So same goes with flags and libs I guess?

## 

Vincent Cogne

**Comment by den-mentiei** [comment]
Indeed, as they are variables and are not threaten in a special way - they are just predefined in core.

**Comment by jimon** [comment]
@xpac27 you can also do like :

```
includedirs = lib/inc
build $out/app/obj(*): auto app/*.cpp
    includedirs += app/inc
```

**Comment by xpac27** [comment]
Perfect. I tried it and it works like a charm. I'm closing the issue ^^
