### ISSUE TITLE
Variable value append shorthand

### ISSUE THREAD

**Issue by den-mentiei** [beardsvibe/buildfox#8]
Can we have `cxxflags += $defines` as a shorthand for `cxxflags = $cxxflags $defines`?

**Comment by jimon** [comment]
A problem with that - somebody will ask for `cxxflags -= ...`, which could be ok, or could be not ok.

I guess better solution for now is to make something like this :

```
rule cxx
    cxxflags_all = $cxxflags $defines $includes ...
    command = cl $cxxflags_all -c $in /Fo:$out

defines = DEFINE1 DEFINE2
build *.obj: cxx *.cpp
```

So there is no need to add defines to cxxflags explicitly.

**Comment by den-mentiei** [comment]
I do not see when `-=` can be useful.
On the other side `+=` is very useful with #7.

**Comment by jimon** [comment]
Ah ok you mean do add stuff while you shadow, yes, this is very useful !

**Comment by jimon** [comment]
Though qmake have =, +=, -=. For some reason they implemented -= and it is used sometimes.

**Comment by den-mentiei** [comment]
I'll poke on it and think on implementing `-=` too. Just after the #7 :)
Can be useful with shadown, though, e.g. disable logging for some lib.
